### ISSUE TITLE
Non-static method Jasny\Auth\Auth::user() should not be called statically

### ISSUE THREAD

**Issue by osamaAbdullah** [jasny/auth#13]
all of the mentioned methods in the documentation are called as static methods, but none of them is static so it gives an error

`Auth::login(string $username, string $password)`
`Auth::loginAs(UserInterface $user)`
`Auth::logout()` ...etc

**Comment by jasny** [comment]
I'm using the same notation as the documentation on php.net.

[![screenshot-www php net-2020 06 19-13_34_31](https://user-images.githubusercontent.com/100821/85128463-9f102b00-b231-11ea-9262-53a51c9d66a2.png)](https://www.php.net/manual/en/datetime.add.php)
