### ISSUE TITLE
Incorrect third param in hash function in HashidsConfirmation.php

### ISSUE THREAD

**Issue by ssulima** [jasny/auth#16]
https://github.com/jasny/auth/blob/d8d0b723fec345c910ec415f0d338f54334c0082/src/Confirmation/HashidsConfirmation.php#L315

Third param in **hash** function generates outputs raw binary data which trigger warnings in **Hashids**. In constructor of **Hashids** salt is encoding but is as binary so `\mb_detect_encoding($salt)` return incorrect encoding type for `\mb_convert_encoding($salt, 'UTF-8', \mb_detect_encoding($salt))`  
https://github.com/vinkla/hashids/blob/8cab111f78e0bd9c76953b082919fc9e251761be/src/Hashids.php#L95

**Comment by jasny** [comment]
Nice case of it's accidentally working :frowning_face:

It's fixed, but it does mean breaking BC.

**Comment by jasny** [comment]
Fixed in v2.1.0
