### ISSUE TITLE
Storing the user object in a session?

### ISSUE THREAD

**Issue by pv4** [jasny/auth#19]
Hello!

According to https://github.com/jasny/auth/blob/53536cfe5e4a37c1f0e2d3d55e9ab23e4b290a4c/src/Auth.php#L145 it's somehow possible to store the User instance in a session instead of storing uid only.

I'd like to use this feature to get rid of extra sql query in Storage::fetchUserById() (i.e. get the User from the session instead of doing an extra sql query(-ies) to get the User from database by uid). But I couldn't find a way to force Jasny/Auth to put the User to the session instead of only putting uid there.

1. Is there such a way?
2. Is there actually such a feature, or did I misunderstand what that "$user instanceof User" is for?

**Comment by jasny** [comment]
That's correct. You can store objects in a PHP Session. Values will be serialized and deserialized. So as long as your object supports serialization, this will work. If your object is something like an active record (with a DB connection) this will cause issues.
