### ISSUE TITLE
Fatal error when trying to implement level based auth follow by example in README.md

### ISSUE THREAD

**Issue by gymadarasz** [jasny/auth#7]
Fatal error: gymadarasz\Auth\Auth and Jasny\Authz\byLevel define the same property ($levels) in the composition of gymadarasz\Auth\Auth. However, the definition differs and is considered incompatible. Class was composed in C:\xampp\htdocs\testauth\src\Auth\Auth.php on line 97

My suugestion, just remove the line `protected static $levels;` from `trait byLevel` in file `byLevel.php` at line ~37

**Comment by jasny** [comment]
No longer applies
